lasdi:
  type:                     gplasdi
  gplasdi:
    lr:                     0.001
    n_samples:              20

    # Note that t_rollout is capped at 0.75 to ensure there are some frames to simulate forward.
    p_rollout_init:         0.01
    rollout_update_freq:    100
    dp_per_update:          0.01
    randomized_rollout:     True    # If true, then the duration is randomized for each IC, with p_rollout acting as a maximum. Otherwise, everything is rolled out by p_rollout.
    rollout_spline_order:   1

    p_IC_rollout_init:      0.01
    IC_rollout_update_freq: 100
    IC_dp_per_update:       0.01

    max_iter:               36000
    n_iter:                 4000
    max_greedy_iter:        36000

    loss_weights:
      recon:                1.0
      LD:                   1.0
      rollout:              1.0
      IC_rollout:           0.0
      coef:                 0.0001

    loss_types:
      recon:                "MSE"
      LD:                   "MSE"
      rollout:              "MSE"
      IC_rollout:           "MSE"

    learnable_coefs:        true

workflow:
  use_restart:              False
  restart_file:            

parameter_space:
  parameters:
    - name:                 w
      min:                  0.9
      max:                  1.1
      test_space_type:      uniform
      sample_size:          11
      log_scale:            false
    - name:                 g
      min:                  1.5
      max:                  1.7
      test_space_type:      uniform
      sample_size:          11
      log_scale:            false
  test_space:
    type:                   grid

model:
  type:                     autoencoder
  autoencoder:
    hidden_widths:          [250, 100, 100, 100]
    latent_dimension:       10  
    activations:            ["sin", "sin", "sin", "sin"]

latent_dynamics:
  type:                     sindy
  coef_norm_order:          fro
  sindy:

physics:
  type:                     Advection
  Advection:
    n_t:                    501
    t_max:                  5.0
    uniform_t_grid:         true


