lasdi:
  type:                     gplasdi
  gplasdi:
    lr:                     0.001
    n_samples:              20

    # Note that t_rollout is capped at 0.75 to ensure there are some frames to simulate forward.
    p_rollout_init:         0.01
    rollout_update_freq:    100
    dp_per_update:          0.01
    randomized_rollout:     True    # If true, then the duration is randomized for each IC, with p_rollout acting as a maximum. Otherwise, everything is rolled out by p_rollout.
    rollout_spline_order:   1

    p_IC_rollout_init:      0.01
    IC_rollout_update_freq: 100
    IC_dp_per_update:       0.01

    max_iter:               20000
    n_iter:                 2500
    max_greedy_iter:        20000

    loss_weights:
      recon:                1.0
      chain_rule:           1.0
      LD:                   1.0
      rollout:              0.0
      IC_rollout:           0.2
      coef:                 0.0001
      consistency:          1.0

    loss_types:
      recon:                "MAE"
      chain_rule:           "MSE"
      LD:                   "MSE"
      rollout:              "MAE"
      IC_rollout:           "MAE"
      consistency:          "MSE"

    learnable_coefs:        true

workflow:
  use_restart:              false
  restart_file:             

parameter_space:
  parameters:
    - name:                 a
      min:                  0.45
      max:                  0.55
      test_space_type:      uniform
      sample_size:          11
      log_scale:            false
    - name:                 w
      test_space_type:      list
      list:                 [.175, .18, .185, .19, .195, .2, .205, .21, .215, .22, .225]
  test_space:
    type:                   grid

model:
  type:                     autoencoder
  autoencoder:
    hidden_widths:          [250, 100, 100, 100]
    latent_dimension:       5  
    activations:            ["sin", "sin", "sin", "sin"]

latent_dynamics:
  type:                     sindy
  coef_norm_order:          fro
  sindy:

physics:
  type:                     Burgers

  Burgers:
    n_t:                    501
    t_max:                  1.
    n_x:                    1001
    x_min:                  -3.
    x_max:                  3.
    maxk:                   10
    convergence_threshold:  0.00000001
    uniform_t_grid:         false


