lasdi:
  type:                     gplasdi
  gplasdi:
    lr:                     0.001
    n_samples:              20

    # Note that t_rollout is capped at 0.75 to ensure there are some frames to simulate forward.
    p_rollout_init:         0.01
    rollout_update_freq:    100
    dp_per_update:          0.01
    randomized_rollout:     true    # If true, then the duration is randomized for each IC, with p_rollout acting as a maximum. Otherwise, everything is rolled out by p_rollout.
    rollout_spline_order:   1

    p_IC_rollout_init:      0.01
    IC_rollout_update_freq: 100
    IC_dp_per_update:       0.01

    max_iter:               17500
    n_iter:                 2500
    max_greedy_iter:        17500

    loss_weights:
      recon:                1.0
      LD:                   1.0
      rollout:              1.0
      IC_rollout:           1.0
      coef:                 0.0001

      chain_rule:           1.0
      consistency:          1.0

    loss_types:
      recon:                "MAE"
      LD:                   "MAE"
      rollout:              "MAE"
      IC_rollout:           "MAE"

      chain_rule:           "MSE"
      consistency:          "MSE"

    learnable_coefs:        true
  
workflow:
  use_restart:              false
  restart_file:          

parameter_space:
  parameters:
    - name:                 A
      test_space_type:      list
      list:                 [0.9, 0.92, 0.94, 0.96, 0.98, 1.0, 1.02, 1.04, 1.06, 1.08, 1.1]
    - name:                 w
      test_space_type:      uniform
      min:                  0.23
      max:                  0.27
      sample_size:          11
      log_scale:            false
  test_space:
    type:                   grid

model:
  type:                     ae
  ae:
    hidden_widths:          [250, 100, 100, 100]
    activations:            ["sin", "sin", "sin", "sin"]
    latent_dimension:       10

latent_dynamics:
  type:                     sindy
  coef_norm_order:          fro
  sindy:

physics:
  type:                     Explicit
  
  Explicit:
    n_t:                    501
    t_max:                  6
    n_positions:            1000
    x_min:                  -2.5
    x_max:                  2.5
    y_min:                  -2.5
    y_max:                  2.5
    uniform_t_grid:         True



